version: '3.7'
services:

  test_vault:
    image: hashicorp/vault:latest
    container_name: test_private_key_vault
    ports:
      - "8201:8200"
    restart: always
    environment:
      - VAULT_DEV_MODE=true
      - VAULT_DEV_ROOT_TOKEN_ID=root
    cap_add:
        - IPC_LOCK
    entrypoint: vault server -dev

  test_postgres:
    image: postgres:latest
    container_name: test_postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always