# Use an official Node.js as the base image
FROM node:alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy proxy configuration file
COPY proxy.conf.json .

# Expose port 8000 (or the port your proxy server listens on)
EXPOSE 8000

# Command to run proxy server
CMD ["npm", "start"]