# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 8080
EXPOSE 8080

# Command to run Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]