version: '3.7'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: private_key_vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./Vault_Data/Logs:/vault/logs
      - ./Vault_Data/File:/vault/file
      - ./Vault_Data/Config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always