namespace UserService.Models.Responses;
public record ShowFriendRequestDto(Guid RequestId, string SenderName, Guid SenderId, DateTime? SentTime, string ReceiverName, Guid ReceiverId);
public record UsernameUserEmailAndTwoFactorEnabledDto(string Username, string Email, bool TwoFactorEnabled);
public record KeyAndIvDto(string EncryptedPrivateKey, string Iv);
public record ImageDto(byte[] ImageBytes, string ContentType);
public record UserNameEmailDto(string Username, string Email);
public record UserEmailDto(string Email);
public record UserNameDto(string UserName);
public record ConnectionDto(Guid UserId, string ConnectionId);
public record UserPrivateKeyDto(string EncryptedPrivateKey);
public record UserPublicKeyDto(string PublicKey);
public record UserIdAndEmailDto(Guid Id, string Email);
public record UserIdDto(Guid Id);
public record UserIdAndConnectionIdDto(Guid UserId, string ConnectionId);
public record NumberDto(int Count);
public record KeysDto(string PublicKey, string PrivateKey);
public record ConnectionIdAndAcceptedTimeDto(Guid ConnectionId, DateTime AcceptedTime);
public record UserIdAndPublicKeyDto(Guid Id, string PublicKey);
public record UserIdAndUserNameDto(Guid Id, string UserName);
public record ReceivedAndSentFriendRequestsDto(IList<ShowFriendRequestDto> Received, IList<ShowFriendRequestDto> Sent);       