name: Publish Docker images

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    env:
      IssueAudience: ${{ secrets.ISSUE_AUDIENCE }}
      ConnectionString: ${{ secrets.CONNECTION_STRING }}
      IssueSign: ${{ secrets.ISSUE_SIGN }}
      AdminEmail: ${{ secrets.ADMIN_EMAIL }}
      AdminUserName: ${{ secrets.ADMIN_USERNAME }}
      AdminPassword: ${{ secrets.ADMIN_PASSWORD }}
      DeveloperEmail: ${{ secrets.DEVELOPER_EMAIL }}
      DeveloperPassword: ${{ secrets.DEVELOPER_PASSWORD }}
      GoogleClientId: ${{ secrets.GOOGLE_CLIENT_ID }}
      GoogleClientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      FacebookClientId: ${{ secrets.FACEBOOK_CLIENT_ID }}
      FacebookClientSecret: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
      FrontendPort: ${{ secrets.FRONTEND_PORT }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for Server Docker image
        id: server_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: thetips4you/server/messageappserver

      - name: Build and push Server Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: Server/MessageAppServer
          push: true
          tags: ${{ steps.server_meta.outputs.tags }}
          labels: ${{ steps.server_meta.outputs.labels }}

      - name: Extract metadata for Client Docker image
        id: client_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: thetips4you/client

      - name: Build and push Client Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ClientApp
          dockerfile: ClientApp
          push: true
          tags: ${{ steps.client_meta.outputs.tags }}
          labels: ${{ steps.client_meta.outputs.labels }}
