name: .NET Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start MSSQL Server Docker container
      run: |
        docker run --name my-mssql-db -e ACCEPT_EULA=Y -e SA_PASSWORD=MyStrongPassword123 -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
        docker exec my-mssql-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P MyStrongPassword123 -Q "SELECT 1"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore Server/Tests/Tests.csproj

    - name: Set up test configuration
      run: echo '${{ secrets.TEST_CONFIG_JSON }}' > testConfiguration.json

    - name: Copy test configuration to project directory
      run: cp testConfiguration.json Server/MessageAppServer

    - name: Build
      working-directory: Server/Tests
      run: dotnet build --configuration Release --no-restore

    - name: Create migrations
      run: dotnet ef migrations add InitialMigration --project Server/MessageAppServer --startup-project Server/MessageAppServer --output-dir Data/Migrations

    - name: Update database
      run: dotnet ef database update --project Server/MessageAppServer --startup-project Server/MessageAppServer

    - name: Test
      working-directory: Server/Tests
      run: dotnet test --no-restore --verbosity normal
