name: .NET Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore Server/Tests/Tests.csproj

    - name: Set up test configuration
      run: echo '${{ secrets.TEST_CONFIG_JSON }}' > testConfiguration.json

    - name: Copy test configuration to project directory
      run: cp testConfiguration.json Server/MessageAppServer

    - name: Build
      working-directory: Server/Tests
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: Server/Tests
      run: dotnet test --no-restore --verbosity normal
